#############################
### BUILD FOR DEVELOPMENT ###
#############################

FROM node:latest AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
